In [1]:
import sys
sys.path.append('/Users/raulferreira/pytorch-ner')

In [2]:
import json

import pandas as pd


In [4]:
nlp = spacy.load("en_core_web_sm", disable=['ner', 'tagger', 'parser', 'textcat'])

nlp.pipe_names

[]

In [33]:
for a, b, c in char_offsets:
    d = {i: c for i in range(a, b+1)}
    print(d)
    break
    
    

{0: 0, 1: 0, 2: 0, 3: 0}


In [35]:
import spacy

from functools import reduce

In [ ]:
nlp = spacy.load("en_core_web_sm", disable=['ner', 'tagger', 'parser', 'textcat'])

In [38]:
string = 'The SCE must send the registrar written notice of — \n  ( a ) the initiation and termination of winding - up , including voluntary winding - up , liquidation or insolvency of the SCE or suspension of the SCE ’s payment procedures and any decision to continue operating the SCE ( within the meaning of Article 74 ) ; and \n  ( b ) the closure of the branch , \n  within one month of that event or decision .'
doc = nlp(string)

403

In [36]:
char_offsets = [(token.idx, token.idx + len(token), token.i) for token in doc]

char_index_to_token_index_mapping = reduce(
    lambda acc, x: {**acc, **x},
    [{i: c for i in range(a, b+1)} for a, b, c in char_offsets],
    dict()
)


# for (a, b, c), t in zip(char_offsets, list(doc)):
#     print(c, doc.text[a:b], '|', t)

In [37]:
char_index_to_token_index_mapping

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 2,
 9: 2,
 10: 2,
 11: 2,
 12: 2,
 13: 3,
 14: 3,
 15: 3,
 16: 3,
 17: 3,
 18: 4,
 19: 4,
 20: 4,
 21: 4,
 22: 5,
 23: 5,
 24: 5,
 25: 5,
 26: 5,
 27: 5,
 28: 5,
 29: 5,
 30: 5,
 31: 5,
 32: 6,
 33: 6,
 34: 6,
 35: 6,
 36: 6,
 37: 6,
 38: 6,
 39: 6,
 40: 7,
 41: 7,
 42: 7,
 43: 7,
 44: 7,
 45: 7,
 46: 7,
 47: 8,
 48: 8,
 49: 8,
 50: 9,
 51: 9,
 52: 10,
 53: 10,
 54: 10,
 55: 11,
 56: 11,
 57: 12,
 58: 12,
 59: 13,
 60: 13,
 61: 14,
 62: 14,
 63: 14,
 64: 14,
 65: 15,
 66: 15,
 67: 15,
 68: 15,
 69: 15,
 70: 15,
 71: 15,
 72: 15,
 73: 15,
 74: 15,
 75: 15,
 76: 16,
 77: 16,
 78: 16,
 79: 16,
 80: 17,
 81: 17,
 82: 17,
 83: 17,
 84: 17,
 85: 17,
 86: 17,
 87: 17,
 88: 17,
 89: 17,
 90: 17,
 91: 17,
 92: 18,
 93: 18,
 94: 18,
 95: 19,
 96: 19,
 97: 19,
 98: 19,
 99: 19,
 100: 19,
 101: 19,
 102: 19,
 103: 20,
 104: 20,
 105: 21,
 106: 21,
 107: 21,
 108: 22,
 109: 22,
 110: 23,
 111: 23,
 112: 23,
 113: 23,
 114: 23,
 115: 23,
 1

In [110]:
file = '/Users/raulferreira/pytorch-ner/data/prodigy-sample-annotation.pickle'


In [111]:
df = pd.read_pickle(file)

In [114]:
' '.join([i['text'] for i in df.iloc[0]['tokens']])

'The SCE must send the registrar written notice of — \n  ( a ) the initiation and termination of winding - up , including voluntary winding - up , liquidation or insolvency of the SCE or suspension of the SCE ’s payment procedures and any decision to continue operating the SCE ( within the meaning of Article 74 ) ; and \n  ( b ) the closure of the branch , \n  within one month of that event or decision .'

In [57]:
data = [json.loads(d) for d in df['data']]

In [67]:
# entries = [(d['text'], d['spans']) for d in data]

df = pd.DataFrame(data)
df.iloc[100:].to_pickle('/Users/raulferreira/pytorch-ner/data/prodigy-sample-annotation.pickle')

In [28]:
sentence = "the court officer must drive away if applicable"
sentence[0:17]

'the court officer'

In [39]:
texts = [
    'This is a sentence',
    "the court officer must drive away if applicable"
]

tokenizer(
            texts,
            return_tensors="pt",
            truncation=True,
            padding='max_length',
            max_length=20,
    return_offsets_mapping=True
        )

print(1)

1


In [7]:
len(data[100]['tokens'])

81

In [52]:
sentence =  "the court officer must drive away if applicable"
sentence = "the court officer must drive away"

enc = tokenizer.encode_plus(sentence, return_offsets_mapping=True)

print(tokenizer.convert_ids_to_tokens(enc['input_ids']))

print(enc['input_ids'])
print(enc['offset_mapping'])

for a, b in zip(tokenizer.convert_ids_to_tokens(enc['input_ids']), enc['offset_mapping']):
    print(a, b)

['<s>', 'the', 'Ġcourt', 'Ġofficer', 'Ġmust', 'Ġdrive', 'Ġaway', '</s>']
[0, 627, 461, 1036, 531, 1305, 409, 2]
[(0, 0), (0, 3), (4, 9), (10, 17), (18, 22), (23, 28), (29, 33), (0, 0)]
<s> (0, 0)
the (0, 3)
Ġcourt (4, 9)
Ġofficer (10, 17)
Ġmust (18, 22)
Ġdrive (23, 28)
Ġaway (29, 33)
</s> (0, 0)


In [20]:
enc = tokenizer.encode_plus("Driving away", return_offsets_mapping=True)

print(enc['input_ids'])
print(enc)

print(tokenizer.convert_ids_to_tokens(enc['input_ids']))

[0, 34002, 6645, 409, 2]
{'input_ids': [0, 34002, 6645, 409, 2], 'attention_mask': [1, 1, 1, 1, 1], 'offset_mapping': [(0, 0), (0, 3), (3, 7), (8, 12), (0, 0)]}
['<s>', 'Dri', 'ving', 'Ġaway', '</s>']


In [11]:
enc = tokenizer.encode_plus(data[100]['text'], return_offsets_mapping=True)
print(enc)


{'input_ids': [0, 133, 208, 8041, 531, 2142, 5, 19886, 17254, 1982, 3120, 9, 93, 1437, 50118, 36, 10, 4839, 5, 34939, 8, 17829, 9, 20058, 111, 62, 2156, 217, 11659, 20058, 111, 62, 2156, 6936, 1258, 50, 23799, 2987, 4469, 9, 5, 208, 8041, 50, 5436, 9, 5, 208, 8041, 44, 27, 29, 3207, 6196, 8, 143, 568, 7, 535, 1633, 5, 208, 8041, 36, 624, 5, 3099, 9, 6776, 6657, 4839, 25606, 8, 1437, 50118, 36, 741, 4839, 5, 6803, 9, 5, 6084, 2156, 1437, 50118, 624, 65, 353, 9, 14, 515, 50, 568, 479, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'offset_mapping': [(0, 0), (0, 3), (4, 5), (5, 7), (8, 12), (13, 17), (18, 21), (22, 28), (28, 31), (32, 39), (40, 46), (47, 49), (50, 51), (52, 52), (52, 53), (54, 55), (56, 57), (58, 59), (60, 63), 

In [94]:
from transformers import PreTrainedTokenizer
from transformers import RobertaTokenizerFast


def make_roberta_tokenizer() -> PreTrainedTokenizer:
    tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")
    return tokenizer


tokenizer = make_roberta_tokenizer()

In [54]:
tokens = nlp("The court officer was driving away")

In [55]:
[str(i) for i in tokens]

['The', 'court', 'officer', 'was', 'driving', 'away']

In [32]:
sentence = "The aerodynamics of the viature are well studied"

sentence[48]

IndexError: string index out of range

In [44]:
import numpy as np


v = np.array([
    [1, 1, 2],
    [2, 3, 6]
])

In [49]:
print(v.mean(axis=0))
np.argmax(v.mean(axis=0))

[1.5 2.  4. ]


2

In [43]:
Out[42].tolist()

[[0.17716151475906372, 0.3453901410102844, 0.6674686074256897],
 [0.6000826954841614, 0.3614288568496704, 0.9698708057403564],
 [0.23562955856323242, 0.4113318920135498, 0.17610770463943481],
 [0.2445020079612732, 0.9833195209503174, 0.6258184909820557],
 [0.08503538370132446, 0.029334187507629395, 0.8442292213439941],
 [0.12422728538513184, 0.43789583444595337, 0.2543674111366272],
 [0.27070826292037964, 0.8785005211830139, 0.9738351106643677],
 [0.5133657455444336, 0.3527209162712097, 0.17843478918075562],
 [0.03944045305252075, 0.7657544016838074, 0.9044941067695618],
 [0.0683826208114624, 0.9502130150794983, 0.780992329120636]]

In [42]:

import torch
torch.rand(10, 3)

tensor([[0.1772, 0.3454, 0.6675],
        [0.6001, 0.3614, 0.9699],
        [0.2356, 0.4113, 0.1761],
        [0.2445, 0.9833, 0.6258],
        [0.0850, 0.0293, 0.8442],
        [0.1242, 0.4379, 0.2544],
        [0.2707, 0.8785, 0.9738],
        [0.5134, 0.3527, 0.1784],
        [0.0394, 0.7658, 0.9045],
        [0.0684, 0.9502, 0.7810]])

In [103]:
sentence = "The aerodynamics of the viature are well studied"

encoded_tokens = ['<s>', 'The', 'Ġaer', 'odynamics', 'Ġof', 'Ġthe', 'Ġvi', 'ature', 'Ġare', 'Ġwell', 'Ġstudied', '</s>']

input_ids = [0, 133, 16482, 41203, 9, 5, 12987, 18830, 32, 157, 8069, 2]

offset_mapping = [
    (0, 0),
    (0, 3),
    (4, 7),
    (7, 16),
    (17, 19),
    (20, 23),
    (24, 26),
    (26, 31),
    (32, 35),
    (36, 40),
    (41, 48),
    (0, 0)
]

enc = tokenizer.encode_plus(sentence, return_offsets_mapping=True)

print(tokenizer.convert_ids_to_tokens(enc['input_ids']))

enc['offset_mapping']

['<s>', 'The', 'Ġaer', 'odynamics', 'Ġof', 'Ġthe', 'Ġvi', 'ature', 'Ġare', 'Ġwell', 'Ġstudied', '</s>']


[(0, 0),
 (0, 3),
 (4, 7),
 (7, 16),
 (17, 19),
 (20, 23),
 (24, 26),
 (26, 31),
 (32, 35),
 (36, 40),
 (41, 48),
 (0, 0)]

In [11]:
import torch

enc = tokenizer.encode_plus("Driving away", return_offsets_mapping=True, max_length=10, truncation=True)

print(enc['input_ids'])
print(enc)

print(tokenizer.convert_ids_to_tokens(enc['input_ids']))

[0, 34002, 6645, 409, 2]
{'input_ids': [0, 34002, 6645, 409, 2], 'attention_mask': [1, 1, 1, 1, 1], 'offset_mapping': [(0, 0), (0, 3), (3, 7), (8, 12), (0, 0)]}
['<s>', 'Dri', 'ving', 'Ġaway', '</s>']


target => torch.Size([16, 280])

y_pred => torch.Size([16, 280, 3])

In [15]:
ids = [    0, 13841,    10,  5375,     9,     5,  2502,    16,   829,    30,
            5,  5644,    55,    87,   501,   360,   137,     5,  1248,   278,
           13,     5,  1500,     7,  1642,  2156,     5,  5644,   531,  2156,
          624,   501,   360,     9,     5, 18245,     9,     5,  2502,  2156,
        18981,     5,    97,  1799,     7,     5,  7069,     8,     5,   461,
          942,  1036,    11,  2410,   549,    50,    45,    93,  1437, 50118,
           36,    10,  4839,    37, 20408,     5,  2502,  2156,  1311,  2188,
           13,   143,   215,  1756, 25606,     8,  1437, 50118,    36,   741,
         4839,    37,  8605,     7,    28,  4625,    23,   143,  1576,     9,
            5,  2502,   479,     2]


a = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


b = [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, -1]

print(len(ids))
print(len(a))
print(len(b))

94
94
94


In [38]:
loss_fct = torch.nn.CrossEntropyLoss()

In [78]:
# attention_mask = torch.tensor([
#     [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
#     [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
#     [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
# ])

target = torch.tensor([
    [-1, 1, 1, 1, -1, -1, -1, -1, -1, -1],
    [-1, 1, 1, 1, 1, 1, 1, -1, -1, -1]  
])

logits = torch.tensor([
    [[0.9672, 0.3671, 0.5196],
     [0.7375, 0.4412, 0.6449],
     [0.5044, 0.9435, 0.1143],
     [0.9318, 0.8636, 0.8863],
     [0.2648, 0.4413, 0.9613],
     [0.7696, 0.5530, 0.9382],
     [0.3856, 0.3141, 0.1020],
     [0.0399, 0.5205, 0.3871],
     [0.3224, 0.1528, 0.6944],
     [0.1538, 0.6460, 0.5724]],

    [[0.2613, 0.2959, 0.1332],
     [0.0477, 0.4868, 0.9213],
     [0.3568, 0.2871, 0.3812],
     [0.2602, 0.8076, 0.6706],
     [0.3575, 0.3397, 0.1995],
     [0.5706, 0.7086, 0.0107],
     [0.9112, 0.2669, 0.1066],
     [0.2189, 0.0382, 0.3898],
     [0.5111, 0.3911, 0.6043],
     [0.3021, 0.5809, 0.4534]]
])

In [81]:
logits.shape[-1]

3

In [83]:
active_loss = target.view(-1) != -1 

active_logits = logits.view(-1, 3)

active_labels = torch.where(
    active_loss, target.view(-1), torch.tensor(loss_fct.ignore_index).type_as(target)
)

print(active_logits)
print(active_logits.shape)
print()
print(active_labels)
print(active_labels.shape)
loss = loss_fct(active_logits, active_labels)

loss.item()

tensor([[0.9672, 0.3671, 0.5196],
        [0.7375, 0.4412, 0.6449],
        [0.5044, 0.9435, 0.1143],
        [0.9318, 0.8636, 0.8863],
        [0.2648, 0.4413, 0.9613],
        [0.7696, 0.5530, 0.9382],
        [0.3856, 0.3141, 0.1020],
        [0.0399, 0.5205, 0.3871],
        [0.3224, 0.1528, 0.6944],
        [0.1538, 0.6460, 0.5724],
        [0.2613, 0.2959, 0.1332],
        [0.0477, 0.4868, 0.9213],
        [0.3568, 0.2871, 0.3812],
        [0.2602, 0.8076, 0.6706],
        [0.3575, 0.3397, 0.1995],
        [0.5706, 0.7086, 0.0107],
        [0.9112, 0.2669, 0.1066],
        [0.2189, 0.0382, 0.3898],
        [0.5111, 0.3911, 0.6043],
        [0.3021, 0.5809, 0.4534]])
torch.Size([20, 3])

tensor([-100,    1,    1,    1, -100, -100, -100, -100, -100, -100, -100,    1,
           1,    1,    1,    1,    1, -100, -100, -100])
torch.Size([20])


1.0656657218933105

In [63]:
active_labels

tensor([-100,    1,    1,    1, -100, -100, -100, -100, -100, -100, -100,    1,
           1,    1,    1,    1,    1, -100, -100, -100, -100,    1,    1, -100,
        -100, -100, -100, -100, -100, -100])

In [43]:
torch.where(
    active_loss, target.view(-1), torch.tensor(loss_fct.ignore_index).type_as(target)
)

tensor([-100,    1,    1,    1, -100, -100, -100, -100, -100, -100, -100,    1,
           1,    1,    1,    1,    1, -100, -100, -100, -100,    1,    1, -100,
        -100, -100, -100, -100, -100, -100])

In [ ]:


active_labels = torch.where(
    active_loss, target.view(-1), torch.tensor(loss_fct.ignore_index).type_as(target)
)

In [50]:
data = [
    [
        [1, 2, 1],
        [0, 1, 0],
        [1, 1, 0],
    ],
    [
        [0, 2, 0],
        [0, 2, 0],
        [2, 2, 0],
    ]    
]
v = torch.tensor(data, dtype=float)

v.shape

torch.Size([2, 3, 3])

In [51]:
for a, b in v:
    print(a)
    print(b)

ValueError: too many values to unpack (expected 2)

In [8]:
v.mean(dim=1)[0]

tensor([0.6667, 1.3333, 0.3333], dtype=torch.float64)

In [84]:
import pandas as pd

df = pd.read_pickle('/Users/raulferreira/pytorch-ner/data/prodigy-sample-annotation.pickle')

In [88]:
df.iloc[:50].to_pickle('/Users/raulferreira/pytorch-ner/data/prodigy-sample-annotation.pickle')

In [90]:
y_true = [[-1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [-1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [-1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]
y_pred = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 2, 2, 2, 1, 1, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0, 2, 0, 0, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]


In [91]:
print(len(y_true))
print(len(y_pred))

5
5


In [92]:
len(y_true[0])

280

In [93]:
len(y_pred[0])

280